apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: phpapp
  name: php-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: phpapp
    spec:
      containers:
      - image: 287301745136.dkr.ecr.us-east-2.amazonaws.com/myphpapp:latest
        name: phpapp
        ports: 
        - name: phpapp
          containerPort: 8085
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: phpapp
  name: phpapp
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    name: phpapp
---